DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS;
DROP TABLE CUSTOMER;
DROP TABLE PRODUCT;

CREATE TABLE CUSTOMER (
      CUST_ID INTEGER NOT NULL  AUTO_INCREMENT,
      customerName VARCHAR(40) NOT NULL,
      orders INTEGER NOT NULL,
      Primary Key (CUST_ID)
);


CREATE TABLE PRODUCT (
      PRODUCT_ID INTEGER NOT NULL AUTO_INCREMENT,
      PRODUCT_NAME VARCHAR(50) NOT NULL,
	  PRICE  DOUBLE PRECISION,
      Primary Key (PRODUCT_ID)
);

CREATE TABLE ORDERS (
      ORDER_ID INTEGER NOT NULL  AUTO_INCREMENT ,
      CUST_ID INTEGER NOT NULL,
      Primary Key (ORDER_ID),
      Foreign Key (CUST_ID) REFERENCES CUSTOMER (CUST_ID)
    );

CREATE TABLE ORDER_DETAIL (
      ORDER_ID INTEGER NOT NULL,
      PRODUCT_ID INTEGER NOT NULL,
      Primary Key (ORDER_ID,PRODUCT_ID) ,
      Foreign Key (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
      Foreign Key (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)

);


INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRICE) 
	VALUES (2001,'Galaxy J5',10000.00);
